### ISSUE TITLE
Is the animals.md doc a one-stop shop? if so . . . 

### ISSUE THREAD

**Issue by mkuzmick** [learninglab-dev/remote-collab#22]
Should you add what they do when they want to make the change and create pull request right there? or link back to editing doc?

**Comment by jsbean** [comment]
Ah, of course! I will pull that in from the [Editing Files](https://github.com/learninglab-dev/remote-collab/blob/master/Tutorials/Files.md) doc.

**Comment by jsbean** [comment]
I'd say for this first tutorial, a new branch / PR isn't necessary. Going straight into `master` should be OK, as the `Projects` directory should be a pretty safe place to experiment.

**Comment by jsbean** [comment]
I put in a brief section on merging directly into `master`, along with a link to the Editing Files doc.

Thanks!
